<div class="navmenu">
    <ul>
        <li><a href="#">Home</a></li>
        <li> <a href="#">Account</a></li>
    </ul>
</div>
<div id="searchbox">
    <form id="form1" name="form1" method="post" action="">
        <label for="textfield"></label>
        <input type="text" name="textfield" id="textfield" class="input-text" />
        <input type="submit" id="search-submit" class="input_submit" value="Search " />
    </form>
</div>
