<?php $this->placeholder('sidebar')->captureStart() ?>
<h2>Account Menu</h2>
    <ul>
        <li><a href="/accounts/index/add">Add Account</a></li>
        <li><a href="/accounts">List Account</a></li>
    </ul>
    <h2>Report</h2>
    <ul>
        <li><a href="#">By location</a></li>
        <li><a href="#">By sales</a></li>
    </ul>
    <h2>New Added Account</h2>
    <ul>
        <li><a href="#">ABDC co.ltd</a></li>
        <li><a href="#">Activemedia</a></li>
    </ul>
<?php $this->placeholder('sidebar')->captureEnd() ?>
