<h1>Tittel</h1>
<div id="tabs" style="width:100%;">
    <div class="action-box">
        <button>Edit</button>
        <button>Delete</button>
        <button>Find Duplicate</button>
        <button>Print</button>
    </div>
    <ul>
        <li><a href="#tabs-1">General</a></li>
        <li><a href="#tabs-2">Details</a></li>
        <li><a href="#tabs-3">Adress</a></li>
    </ul>
    <div class="white">
        <div id="tabs-1" class="h250">
            <table width="100%" border="0" cellpadding="0" cellspacing="0">
                <tr>
                    <td class="txr w120">Account Name :</td>
                    <td width="37%" nowrap="nowrap" class="b-bottom"><a href="../test.html">Activemedia</a></td>
                    <td class="txr w120">Account No :</td>
                    <td class="b-bottom">DR-00233</td>
                </tr>
                <tr>
                    <td class="txr">Parent Account :</td>
                    <td class="b-bottom">&nbsp;</td>
                    <td class="txr">Main Phone :</td>
                    <td class="b-bottom">02 6525100 to 99</td>
                </tr>
                <tr>
                    <td class="txr">Primary Contact :</td>
                    <td class="b-bottom">&nbsp;</td>
                    <td class="txr">Other Phone :</td>
                    <td class="b-bottom">02 6835100</td>
                </tr>
                <tr>
                    <td class="txr">Relationship Type :</td>
                    <td class="b-bottom">&nbsp;</td>
                    <td class="txr">Fax :</td>
                    <td class="b-bottom">02 6835100</td>
                </tr>
                <tr>
                    <td class="txr">Account Type :</td>
                    <td class="b-bottom">&nbsp;</td>
                    <td class="txr">Email :</td>
                    <td class="b-bottom">info@activemedia.co.th</td>
                </tr>
                <tr>
                    <td class="txr">Assigned To :</td>
                    <td class="b-bottom">&nbsp;</td>
                    <td class="txr">Web Site :</td>
                    <td class="b-bottom">www.activemedia.co.th</td>
                </tr>
                <tr>
                    <td class="txr">Laste Modifed :</td>
                    <td class="b-bottom">{date - time} By : {username} <a href="#">Log</a></td>
                    <td class="txr">Created :</td>
                    <td class="b-bottom">{date - time} By : {username}</td>
                </tr>
            </table>
        </div>
        <div id="tabs-2" class="h250">
            <div class="header-text">
                Business Information :
            </div>
            <table width="100%" border="0" cellpadding="0" cellspacing="0">
                <tr>
                    <td class="txr w120">Industry :</td>
                    <td width="37%" class="b-bottom">Retail Shop;</td>
                    <td class="txr w120">Ownership :</td>
                    <td class="b-bottom">Company limited</td>
                </tr>
                <tr>
                    <td class="txr">Annual Revenue :</td>
                    <td class="b-bottom">100,000. THB</td>
                    <td class="txr">&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
            </table>
            <div class="header-text" style="margin-top:10px;">Descripton :</div>
            <table border="0" cellspacing="0" cellpadding="0">
                <tr>
                    <td> Bla bla bla</td>
                </tr>
            </table>
        </div>
        <div id="tabs-3" class="h250">
            <table width="100%" border="0" cellpadding="0" cellspacing="0">
                <tr>
                    <th class="w200">Billing Adresse</th>
                    <th>&nbsp;</td>
                    <th class="w200">Shipping Adresse</th>
                    <th>&nbsp;</th>
                </tr>
                <tr>
                    <td class="txr">Adresse Name :</td>
                    <td class="b-bottom"><label for="textfield3"></label></td>
                    <td class="txr">Adresse Name :</td>
                    <td class="b-bottom">&nbsp;</td>
                </tr>
                <tr>
                    <td class="txr">Street 1 :</td>
                    <td class="b-bottom">&nbsp;</td>
                    <td class="txr">Street 1 :</td>
                    <td class="b-bottom">&nbsp;</td>
                </tr>
                <tr>
                    <td class="txr">District/Subdivson :</td>
                    <td class="b-bottom">&nbsp;</td>
                    <td class="txr">District/Subdivson :</td>
                    <td class="b-bottom">&nbsp;</td>
                </tr>
                <tr>
                    <td class="txr">Province :</td>
                    <td class="b-bottom">&nbsp;</td>
                    <td class="txr">Province :</td>
                    <td class="b-bottom">&nbsp;</td>
                </tr>
                <tr>
                    <td class="txr">City :</td>
                    <td class="b-bottom">&nbsp;</td>
                    <td class="txr">City :</td>
                    <td class="b-bottom">&nbsp;</td>
                </tr>
                <tr>
                    <td class="txr">Postal Code :</td>
                    <td class="b-bottom">&nbsp;</td>
                    <td class="txr">Postal Code :</td>
                    <td class="b-bottom">&nbsp;</td>
                </tr>
                <tr>
                    <td class="txr">Country :</td>
                    <td class="b-bottom">&nbsp;</td>
                    <td class="txr">Country :</td>
                    <td class="b-bottom">&nbsp;</td>
                </tr>
            </table>
        </div>
    </div>
</div>