<h1>Tittel</h1>
<!--Filter box-->
<div class="filterbox ui-widget-content ui-corner-all"><strong>Search : </strong>
    <form id="form1" name="form1" method="post" action="">
        <label for="textfield"></label>
        <input type="text" name="textfield" id="textfield" />
        in
        <label for="select"></label>
        <select name="select" id="select">
            <option value="#">Account Name</option>
            <option value="#">Phone no</option>
        </select>
        <input type="submit" name="button" id="button" value="Submit" />
        <input type="submit" name="button2" id="button2" value="Show All" />
    </form>
</div>
<div class="ui-widget-content ui-corner-bottom">
    <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr class="txl">
            <th nowrap="nowrap" style="width:20px" scope="col"><a href="#">Action</a></th>
            <th nowrap="nowrap" scope="col"><a href="#">Account Name</a><img  src="images/arrow.gif" alt="" width="8" height="10" border="0" class="sort" /></th>
            <th  nowrap="nowrap" style="width:100px" scope="col">City<img alt=""  src="images/arrow.gif" width="8" height="10" class="sort" /></th>
            <th nowrap="nowrap" style="width:80px" scope="col">Type<img alt=""  src="images/arrow.gif" width="8" height="10" class="sort" /></th>
        </tr>
        <tr onmouseover="this.style.background='#F3F5F5'" onmouseout="this.style.background='white'";>
            <td align="center" class="b-bottom"><input type="checkbox" name="checkbox" id="checkbox" />
                <label for="checkbox"></label></td>
            <td align="left" class="b-bottom"><a href="/accounts/index/detail">Hello</a></td>
            <td class="b-bottom">Bangkok</td>
            <td class="b-bottom">Client</td>
        </tr>
        <tr class="gray">
            <td align="center" class="b-bottom"><input type="checkbox" name="checkbox" id="checkbox" />
                <label for="checkbox"></label></td>
            <td class="b-bottom">hello</td>
            <td class="b-bottom">Bangkok</td>
            <td class="b-bottom">Client</td>
        </tr>
        <tr>
            <td align="center" class="b-bottom"><input type="checkbox" name="checkbox" id="checkbox" />
                <label for="checkbox"></label></td>
            <td class="b-bottom">Hello</td>
            <td class="b-bottom">Bangkok</td>
            <td class="b-bottom">Client</td>
        </tr>
    </table>
    <!--pagination-->
    <table class="pagination" width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
            <td class="b-bottom" width="62%">First | &lt; <a href="../sdfsdf">Previous</a> | 1 | 2 | <a href="../sdf">Next</a> &gt; | <a href="../sdf">Last</a></td>
            <td width="38%" class="txr b-bottom">From: 1 To 20 of Total Record: 29</td>
        </tr>
        <tr>
            <td colspan="2"><ul>
                    <li>All </li>
                    <li><a href="#" title="test">#</a></li>
                    <li>A</li>
                    <li>B</li>
                    <li>C</li>
                    <li>D</li>
                    <li>E</li>
                    <li>F</li>
                    <li>G</li>
                    <li>H</li>
                    <li>I</li>
                    <li>J</li>
                    <li>K</li>
                    <li>L</li>
                    <li>M</li>
                    <li>N</li>
                    <li>P</li>
                    <li>Q</li>
                    <li>R</li>
                    <li>S</li>
                    <li>T</li>
                    <li>U</li>
                    <li>V</li>
                    <li>W</li>
                    <li>X</li>
                    <li>Y</li>
                    <li>Z</li>
                </ul></td>
        </tr>
    </table>
</div>