<h2>Welcome!</h2>
<p>Welcome to SQUARE, our cutting-edge Web search application for rare
stamps.</p>
<p>We have a wide collection of stamps in our catalog for your
browsing pleasure, and we also list <strong>hundreds of thousands of
stamps</strong> from individual collectors across the country. If
you find something you like, drop us a line and we'll do our best to
obtain it for you. Needless to say, all stamps purchased through us
come with a certificate of authenticity, and <strong>our unique 60-day
money-back guarantee</strong>.</p>
<p>The SQUARE application is designed to be as user-friendly as
possible. Use the links in the menu above to navigate and begin
searching.</p>